// Test comment 
//// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzH6_tCt2bqEGu0WwJKY8m_B3QoX7fdR8',
    appId: '1:266920629394:web:675effcd73bfc57fad424b',
    messagingSenderId: '266920629394',
    projectId: 'book-journal-68a53',
    authDomain: 'book-journal-68a53.firebaseapp.com',
    storageBucket: 'book-journal-68a53.firebasestorage.app',
    measurementId: 'G-E488MVRXBK',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzH6_tCt2bqEGu0WwJKY8m_B3QoX7fdR8',
    appId: '1:266920629394:web:675effcd73bfc57fad424b',
    messagingSenderId: '266920629394',
    projectId: 'book-journal-68a53',
    authDomain: 'book-journal-68a53.firebaseapp.com',
    storageBucket: 'book-journal-68a53.firebasestorage.app',
    measurementId: 'G-E488MVRXBK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe2-fVGkh97n2mB5Lc8znQ_cmTlJCQKGc',
    appId: '1:266920629394:ios:8a9c5c257d3d6360ad424b',
    messagingSenderId: '266920629394',
    projectId: 'book-journal-68a53',
    storageBucket: 'book-journal-68a53.firebasestorage.app',
    iosBundleId: 'com.example.bookJournal',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe2-fVGkh97n2mB5Lc8znQ_cmTlJCQKGc',
    appId: '1:266920629394:ios:8a9c5c257d3d6360ad424b',
    messagingSenderId: '266920629394',
    projectId: 'book-journal-68a53',
    storageBucket: 'book-journal-68a53.firebasestorage.app',
    iosBundleId: 'com.example.bookJournal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwg9UvRQIM79Lh0UHS5KoQR05E5Kcq1Xg',
    appId: '1:266920629394:android:ee55a743825e0495ad424b',
    messagingSenderId: '266920629394',
    projectId: 'book-journal-68a53',
    storageBucket: 'book-journal-68a53.firebasestorage.app',
  );

}